# This is a basic workflow to help you get started with Actions
name: Manifest and README.src.rst

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run creating manifest
        run: make manifest
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Run creating README.rst
        run: make README.rst
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes to Manifest and README.rst
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
          # Optional: Skip internal call to `git fetch`
          skip_fetch: true
